### ISSUE TITLE
App.close() should allow to terminate

### ISSUE THREAD

**Issue by wernight** [sikuli/sikuli#22]
`App.close()` seem to nicely ask, which is good, but it should then forcefully terminate/kill the process. 

An optional argument, or a `App.terminate()` or `App.kill()` may be possibly if an automatic terminate/kill after 15 sec or so seems wrong.

**Comment by wernight** [comment]
And it should terminate the whole process tree.

**Comment by wernight** [comment]
I should add that the only moment I had issues is on Windows while running Sikuli with java (not javaw) and spawning a console process. One could close, another app doesn't.

Outside of the fact that this is pretty useful, having the `App.open()` create a new console window (even in java CLI mode) would may help in the general case too.

**Comment by RaiMan** [comment]
The whole App class is very system dependent and very different on the 3 systems (Windows, Mac Linux).
It should be rethinked and rewritten totally.

The current implementation would not allow, to do anything in your wishes' direction.

I have it on my list, but with low priority, since there are always other means in and outside a script, to manage the environment. Something for version X-1.1 maybe ;-)

If you are familiar with native programming on Windows, feel free to suggest a solution.

**Comment by O2F** [comment]
What i will type its not the solution for the problem :) but it can be used as a workaround sometimes.
You can do the App.close() followed by waitVanish({image}, {timeout}) [assuming its not running on background]. 
If it exceed the {timeout} time, you can use App.open("taskkill /f /im {process_name}") [for Windows, Linux and Mac have some instruction too] to forcefully terminate it.

**Comment by ksiv** [comment]
It seems I have the opposite issue on windows. 
Looks like App.close() terminates firefox _from time-to time_ so it requires safe start upon next start. 
I use  App.close in every use case no matter test results because I perform screenshot on failure.
My current setup has no fixture that is why it's an issue, but it's not critical at all, could be passed by using fixtures for example. The idea is: even if sikuli is modified to do like "that" instead of "this", no warranty "that" would work.

**Comment by xar3f** [comment]
using App.terminate and this error shows - [error] AttributeError ( type object 'org.sikuli.script.App' has no attribute 'terminate' ).For open using this one App.open("C:\Program Files (x86)\Internet Explorer\iexplore").using Win8x64 if it matters.

**Comment by RaiMan** [comment]
No longer supported
