### ISSUE TITLE
Publish a Chocolatey package

### ISSUE THREAD

**Issue by AnthonyMastrean** [sikuli/sikuli#8]
Chocolatey is a package manager for Windows. I've [created](https://github.com/AnthonyMastrean/nugetpackages/tree/sikuli/sikuli) a [package](http://chocolatey.org/packages/sikuli) that installs the portable Sikuli and puts an environment (x86/x64) specific link on the Desktop. I'd be happy to provide the spec/script file to your repo (so your team can own it).

It would be cool to have this tied into whatever build/publish system you've got going on in Hudson. But, basically, you just increment the version number in the nuspec file. Update the static zip path in the install script. And repackage and publish to http://chocolatey.org.

I can share information, helper scripts, etc with you.

**Comment by RaiMan** [comment]
looks great (principally ;-)

But the differing version information (1.0.3) is irritating. And it is Sikuli X we are talking about.

I had a look into the installer:
You are referencing the zipped version. But I cannot see, that you are configuring the system path accordingly or set %SIKULI_HOME%.
You differentiate between 32 and 64 Bit, but Sikuli-IDE.bat and Sikuli-IDE-w.bat have nothing to do with that.
The first one leaves the command window open and the second one closes it before bringing up the IDE's window.
Both batch files contain code, to load the java command in its 32-Bit version on both systems.

**Comment by AnthonyMastrean** [comment]
### Version

I don't understand what you're saying about the version information. Did I specify it incorrectly? I took the liberty of turning 1.0 RC3 (r905) into 1.0.3 (Chocolatey sort of depends on [semantic versioning](http://semver.org/)).

We have been trying to reserve the 4th version segment for the package version. In the case where you make a mistake in the package, and have to change something, repackage, and republish. (which I'll probably do once we resolve the issues below!)

### Sikuli HOME

I've been using this package and haven't run into any problems. What does the `%SIKULI_HOME%` variable control? I can certainly set that up.

### Batch File

I haven't looked closely at the batch files. I see what they're doing now. Somewhere on the download page, it said that x64 users need to run the `-w` batch file. Maybe that is incorrect information?

Here it is (however, I just tried both on my x64 Windows and they both worked).

> Sikuli-X-1.0rc3 (r905)-win32.zip (Portable version for 32bit Windows. For 64bit Windows, please run the Sikuli-IDE-w.bat instead of Sikuli-IDE.exe. )

**Comment by RaiMan** [comment]
### Version

Ok, accepted. But then you should change the headline to "Sikuli X 1.0.3" and add a short comment, that the user knows, he gets what officially is called Sikuli X 1.0rc3 (because this is how we talk at the launchpad Q&A and bugs about it)
And if I understand semantic versioning right, you should add a +build.905 or just +905

One more thing: is it possible, to show already in the Sikuli page, that Java 6 is required. Some people run into problems, because they already have Java 7 on their machines.

### %SIKULI_HOME%

When using the installer version (.exe), the system path entries (path-to-Sikuli\libs and path-to-java\jre6\bin) and the environment variable %SIKULI_HOME% pointing to the folder where Sikuli is installed are setup by the installer.
When using the zip download, you have to do it yourself.
%SIKULI_HOME% is needed for some special cases, when running scripts from command line.

### Batch File

The cited text from the home page is a bit misunderstandable: What it wants to say is: on 64Bit Windows do not use the .exe (it simply does not work) but one of the .bat's instead.

**Comment by AnthonyMastrean** [comment]
I'm going to open issues to make it easier to discuss the individual items. We can revisit this pull request when every issue is addressed. Cool?
- Package name (I have some questions)
- Version
- sikuli_home
- batch file
- Java Runtime dependency

**Comment by RaiMan** [comment]
So I close this one now.
